# Generated by Django 4.0.3 on 2022-04-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=10, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=12, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=12, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('grade', models.IntegerField(blank=True, verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата провидения занятия')),
                ('class_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Список учащихся')),
                ('subject', models.ManyToManyField(to='main.schoolsubject', verbose_name='Предметы')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Учашиеся'),
        ),
    ]
