# Generated by Django 4.0.3 on 2022-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_class_students_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(default='7a', max_length=3, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
