# Generated by Django 4.0.3 on 2022-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_journal_class_students_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='class_students',
        ),
        migrations.AddField(
            model_name='journal',
            name='class_students',
            field=models.ManyToManyField(to='main.student', verbose_name='Список учащихся'),
        ),
    ]
